const CASES = 
`
________ Schneller brauner Fuchs springt über ________ fauler Hund. (The) (the)
________ Mama versucht, cool zu sein, indem sie sagt, dass sie alle ________ gleichen Dinge mag, die ich tue. (My) (the)
________ Purple Pig und ________ Green Esel flogen ________ Kite in ________ Mitte ________ Nacht und endete mit Sonnenbrand. (A) (a) (a) (the) (the)
Letzten Freitag sah ich, wie ________ Striped Blue Wurm mit ________ Beinless Eidechse den Hand schüttelt. (a) (a)
________ Song kann ________ Personentag machen oder ruinieren, wenn sie es ihnen erreichen lassen. (A) (a)
Manchmal ist es besser, einfach von den Dingen wegzugehen und später zu ihnen zurückzukehren, wenn Sie in ________ besserer Geistesrahmen sind. (a)
Das Schreiben von ________ Liste zufälliger Sätze ist schwieriger, als ich zunächst dachte. (a)
Seien wir alle zusammen einzigartig, bis wir erkennen, dass wir alle gleich sind. (the)
Wenn Sie Thunfisch und Tomatensauce mögen, versuchen Sie, ________ Two zu kombinieren, es ist wirklich nicht so schlimm, wie es sich anhört. (the)
Als ich klein war, hatte ich ________ Auto -Tür auf ________ Hand zugeschlagen und ich erinnere mich noch sehr lebhaft daran. (a) (my)
________ Uhr Innerhalb dieses Blogs und ________ Uhr auf ________ Laptop unterscheiden sich 1 Stunde voneinander. (The) (the) (my)
Ich möchte ________ Onesie kaufen ... aber weiß, dass es mir nicht passt. (a)
Ich war sehr stolz auf ________ Spitzname während der gesamten High School, aber heute konnte ich mich nicht von dem ________ Spitznamen unterscheiden. (my) (my)
Ich sehe oft ________ Zeit 11:11 oder 12:34 auf Uhren. (the)
Dies ist ________ letzter zufälliger Satz, den ich schreiben werde, und ich werde mitten im Sent aufhören (the)
Wir müssen ________ Zimmer für ________ Party mieten. (a) (our)
Ja, ich denke, ________ ________ gutes Umfeld für das Lernen von Englisch. (it's) (a)
________ Lake ist ________ langer Weg von hier. (The) (a)
Dies ist ________ japanische Puppe. (a)
Sie war zu kurz, um über ________ Zaun zu sehen. (the)
Er erzählte uns ________ sehr aufregende Abenteuergeschichte. (a)
Sie spricht immer mit ihm mit lauter Stimme mit ihm. (a)
Ich wäre lieber ________ Vogel als ________ Fisch. (a) (a)
Mary spielt ________ Klavier. (the)
Sie tat ________ am besten, um ihm zu helfen. (her)
Sie hat sich vor vielen Jahren ________ Book von ihm geliehen und hat es noch nicht zurückgegeben. (the)
Sie schrieb ihm ________ Long Last, aber er hat ihn nicht gelesen. (a)
Bitte warten Sie außerhalb von ________ House. (the)
Tom bekam ________ kleines Stück Kuchen. (a)
Sie faltete ________ Taschentuch ordentlich zusammen. (her)
Wir haben im Juni viel Regen. (a)
Treten Sie nicht auf ________ zerbrochenes Glas. (the)
Lassen Sie mich Ihnen mit ________ Gepäck helfen. (your)
________ Buch befindet sich vor ________ Tisch. (The) (the)
________ mysteriöses Tagebuchaufzeichnungen ________ Voice. (The) (the)
________ Fremder amtiert ________ Mahlzeit. (The) (the)
________ Shooter verabschiedet sich von ________ Liebe. (The) (his)
________ glitzerndes Juwel reicht nicht aus. (A)
________ Speicher, das wir zum Teilen verwendet haben, ist nicht mehr kohärent. (The)
________ alter Apfel schwelgt in seiner Autorität. (The)
________ River stahl ________ Götter. (The) (the)
Joe machte ________ Zuckerkekse;Susan dekorierte sie. (the)
________ Himmel ist klar;________ Sterne funkeln. (The) (the)
________ Wellen stürzten an ________ Ufer ab;Es war ________ schöner Anblick. (The) (the) (a)
In ________ Stadt gab es Weißausgaben;Anschließend waren ________ Straßen unpassierbar. (the) (the)
Schauen Sie morgen wieder vorbei;Ich werde sehen, ob ________ Buch angekommen ist. (the)
Ich freue mich, ________ Spende zu nutzen;Jeder Betrag wird sehr geschätzt. (your)
Sie arbeitet zwei Jobs, um über die Runden zu kommen.Zumindest war das ________ Grund, keine Zeit zu haben, sich uns anzuschließen. (her)
Italien ist ________ Lieblingsland;Tatsächlich habe ich vor, nächstes Jahr zwei Wochen dort zu verbringen. (my)
Er hat am Freitag ________ Research Paper abgelegt;Andernfalls hätte er ________ Klasse nicht bestanden. (the) (the)
Sie war nicht betrügt, ob ________ Test war, denn es war nicht ________ Richtige. (the) (the)
Ich denke, ich werde ________ rotes Auto kaufen, oder ich werde ________ blau mieten. (the) (the)
Ich zähle ________ Kalorien, aber ich möchte wirklich Dessert. (my)
In ________ Gefrierschrank gab es weder Eis, noch hatten sie Geld, um in den ________ Store zu gehen. (the) (the)
Alle waren beschäftigt, also ging ich alleine zum ________ Film. (the)
Ich hätte ________ Promotion bekommen, aber ________ Die Teilnahme war nicht gut genug. (the) (my)
Er wollte nicht zu ________ Zahnarzt gehen, aber er ging trotzdem. (the)
Manchmal starre ich auf ________ Tür oder ________ Wand und ich frage mich, was diese Realität ist, warum ich am Leben bin und worum es geht? (a) (a)
Alles, was Sie tun müssen, ist ________ Stift abzuholen und zu beginnen. (the)
Hätte er gewusst, was passieren würde, wäre er nie in ________ Dusche eingetreten. (the)
Sie hatte nicht ________ Tasse Kaffee gehabt, und das machte die Dinge alles schlimmer. (her) (the)
Alles, was sie wollte, war ________ Antwort, aber sie hatte keine Ahnung, wie sehr sie es hassen würde. (the)
Er kehrte zu ________ Video zurück, um zu sehen, was aufgenommen worden war, und war schockiert über das, was er sah. (the)
Hinter ________ Fenster war ________ Reflexion, die nur Angst veranlasste. (the) (a)
Sie konnte ihn in ________ Dusche mit ________ Freude singen hören. (the) (a) (the)
Als er ________ Fenster schaute, sah er ________ Clown vorbeigehen. (the) (a)
Es hätte ________ Zeit und ________ Ort geben sollen, aber das war es nicht. (a) (a)
Es war ________ bester Sandbecher, den er je gesehen hatte. (the)
Es gibt eine Kunst, ________ zu bekommen und Olivengruben über ________ Tisch zu spucken, nicht wahr? (your) (the)
Natürlich liebt sie ________ Pink Bunny Pantoffeln. (her)
Legen Sie keine Erdnussbutter auf die Nase des Hunde. (the)
Sie kann ________ Leben leben, aber sie will, solange sie auf das hört, was ich zu sagen habe. (her)
Es gibt nur wenige Dinge im Leben besser als ________ Kuchenscheibe. (a)
________ Messer waren draußen und sie schärfte ihre. (The)
Sie fühlte, dass Chill, der ________ Haare auf ________ Rücken des ________ Nackens macht, als er in das ________ Zimmer ging. (the) (the) (your) (the)
Pissen Sie nicht in ________ Garten und sagen Sie mir, dass Sie versuchen, ________ Pflanzen zu wachsen. (my) (my)
Er fand ________ Ende von ________ Rainbow und war überrascht, was er dort fand. (the) (the)
Zwei weitere Tage und alle ________ Probleme würden gelöst. (his)
Es gibt ________ Grund, warum Rosen Dornen haben. (a)
Er schaute hinter ________ Tür und mochte nicht, was er sah. (the)
Er fummelte in ________ Dunkelheit und suchte nach ________ Lichtschalter, aber als er es schließlich fand, war schon jemand da. (the) (the)
Er bellte ________ Töchter den Befehl, aber sie starrten nur amüsiert zurück. (his)
Er hatte ________ versteckte Versteck unter ________ Dielen in ________ Hinterzimmer des ________ House. (a) (the) (the) (the)
Niemand liebt ________ Schwein, das Lippenstift trägt. (a)
Sie rief immer wieder ________ Namensnamen heraus, waren aber nichts als Stille. (her)
Er hatte versehentlich auf ________ Firmenserver gehackt. (his)
Es klingt nicht so, als würde das jemals auf ________ Reiseliste stehen. (my)
Er schwor, dass er nur ________ Sushi bewegte. (his)
Er hatte einen Punkt erreicht, an dem er paranoid war, paranoid zu sein. (the)
________ Sun hatte gesetzt und auch ________ Träume. (The) (his)
Er lernte ________ Wichtige Lektion, dass ________ Picknick am ________ Beach am ________ Windy Day ________ schlechte Idee ist. (the) (a) (the) (a) (a)
Er beobachtete ________ Warnung nicht und es war überraschend gut geworden. (the)
Es war ________ rutschiger Hang und er war bereit, alle ________ Wege in die tiefsten Tiefen zu schieben. (a) (the) (the)
Er würde nur überleben, wenn er ________ Feuer am Laufen hielt und er in ________ Distanz Donner hören konnte. (the) (the)
________ Vertrauen hätte Bienen bewundernswert, wenn es ________ Dummheit nicht wäre. (His) (his)
Sie ließ ________ Ballon mit ________ Hoffnungen und Träumen in ________ Luft schweben. (the) (the) (her)
________ Siebenschichtkuchen hatte nur sechs Schichten. (his)
Es gab Kohle in ________ Strumpf und er war begeistert. (his)
________ Rusty Nagel stand aufrecht, abgewinkelt im ________ 45-Grad-Winkel und wartete nur darauf, dass ________ perfektes Barfuß kommt. (The) (a) (the)
So lang und danke für ________ Fisch. (the)
________ zufälliger Satzgenerator generiert ________ zufälliger Satz über ________ zufälliger Satz. (The) (a) (a)
Sie sagt, sie hat ________ Fähigkeit, ________ Soundtrack des Lebens zu hören. (the) (the) (your)
________ Ironie ________ Situation war für niemanden im ________ Zimmer verloren. (The) (the) (the)
________ Wahrheit ist, dass Sie in Stunden für ________ Lebensstil bezahlen. (The) (your)
________ Licht im ________ Leben war eigentlich ________ Feuer, das überall um ihn herum brannte. (The) (his) (a)
Nichts schien außer ________ Waschmaschine in ________ Bar fehl am Platz zu sein. (the) (the)
Er beschloss, ________ Leben durch ________ Big Beats Manifesto zu leben. (his) (the)
________ geheime Zutat für ________ Wunderbares Leben war Verbrechen. (The) (his)
Er saß in ________ Mülldose mit High Street -Klasse. (a)
________ Tatsache, dass es ________ Treppe zum Himmel gibt, und ________ Autobahn in die Hölle erklärt das Leben gut. (The) (a) (a)
Ich traf eine interessante Schildkröte, während ________ Song auf ________ Radio weggeschossen wurde. (the) (the)
In ________ Ende erkannte er, dass er Klang sehen und Worte hören konnte. (the)
________ Fische hörten aufmerksam zu, was ________ Frösche zu sagen hatten. (The) (the)
Er trat vorsichtig auf die ________ Brücke und wusste, dass Verzauberung auf ________ andere Seite wartete. (the) (the)
Er lernte ________ am härtesten Lektion des Lebens ________ und hatte ________ Narben, sowohl körperlich als auch mental, um es zu beweisen. (the) (his) (the)
In diesem Moment erkannte sie, dass sie ________ Sechster Sinn hatte. (a)
Sie sah keine Ironie, die mich bat, mich zu ändern, aber ich wollte, dass ich ________ so akzeptiere, wie sie ist. (her)
________ Fuchs in ________ Tophat flüsterte in ________ Ohr von ________ Kaninchen. (The) (the) (the) (the)
________ Minute sie landete sie sie verstand ________ Grund, warum dies ________ Fly-Over-Staat war. (The) (the) (a)
Ich wollte dir nur sagen, dass ich sehen konnte ________ LIEBE du für ________ Kind von ________, wie du sie ansiehst. (the) (your) (the)
Er war bereit, ________ Tiefen von ________ Kaninchenloch zu finden, um bei ihr zusammen zu sein. (the) (the)
Sie trug einen grünen Lippenstift wie ________ Mode -Ikone. (a)
Unterschätzen Sie niemals ________ Bereitschaft von ________ gierig, Sie unter ________ Bus zu werfen. (the) (the) (the)
Sie verstand schließlich, dass Trauer ________ Liebe war, ohne dass es für sie geht. (her)
Jede Person, die Sie kennt, hat ________ unterschiedliche Wahrnehmung, wer Sie sind. (a)
________ Schönheit des ________ afrikanischen Sonnenuntergangs verkleidet ________ Gefahr, die in der Nähe lauern. (The) (the) (the)
Sie rannten ________ Ecke herum, um festzustellen, dass sie in der Vergangenheit zurückgefahren waren. (the)
Zufällige Wörter vor anderen zufälligen Wörtern erzeugen ________ zufälligen Satz. (a)
________ Body Piercing ging nicht genau so, wie er erwartet hatte. (The)
________ Schweine wurden beleidigt, dass sie Hamburger genannt wurden. (The)
Als er darauf wartete, dass ________ Dusche warm, bemerkte er, dass er Wassertemperatur wechselte. (the)
Er warf einen Blick auf das, was unter ________ Tisch stand, und noped ________ Hölle da raus. (the) (the)
Sie fand ________ komplette Mattheit interessant. (his)
________ Effizienz, die wir beim Entfernen von Müll haben, hat die Erstellung von Müll akzeptabler gemacht. (The)
________ Gelegenheit zu ________ Leben vor ihm, als er versuchte, zwischen ________ Kegel oder ________ Tasse zu entscheiden. (The) (a) (a) (a)
Eine kleine Aktion würde das Leben ________ verändern, aber ob es für besser oder zum Schlechten sein würde, musste noch bestimmt werden. (her)
Es war ________ Knappheit, die ________ Kreativität trug. (the) (his)
Er fiel zu 100% mit ________, bis er verstand, dass er nicht essen konnte. (her)
Dienstags sind kostenlos, wenn Sie ________ GNOME -Kostüm mitbringen. (a)
________ Publikum schreit und schreit nach mehr Meme. (The)
Sie werfen Kohl, das ________ Gehirn in emotionales Gepäck verwandelt. (your)
Es wäre ________ Bessere Nacht gewesen, wenn ________ Jungs neben uns nicht in ________ Spritzzone gewesen wären. (a) (the) (the)
Ich erwischte ________ Eichhörnchen, das durch ________ Fitnessbeutel raschelte. (my) (my)
Sie haben mich den ganzen Tag beobachtet und auf ________ bewegt wie ________ Löwe ________ Gazelle in ________ Savannah. (your) (a) (a) (a)
________ Nicht oft finden Sie ________ feuge Banane in der ________ Straße. (It's) (a) (the)
Wenn Sie alle ________ möglichen Möglichkeiten berücksichtigen, sich selbst und ________ Welt zu verbessern, bemerkt Sie, dass John Travolta ziemlich unglücklich erscheint. (the) (the)
Ich kaufte ________ Baby Clown vom ________ Russischen Terroristenschwarzmarkt. (a) (the)
Sie erkennen, dass Sie nicht allein sind, wenn Sie in ________ Schlafzimmer ________ Kälber nach ________ langem Tag des Spiels mit Opa Joe in ________ Hospital sitzen. (your) (your) (a) (the)
Sie sind sich nicht sicher, ob Sie ihm vertrauen oder nicht, aber sehr dankbar, dass Sie ________ Turtle Neck trugen. (a)
________ Freundin kaufte ________ Lieblings -Keks -Crisp -Müsli, hat aber vergessen, Milch zu bekommen. (Your) (your)
Er ist gut darin, Gurken zu essen und Frauen von ________ emotionalen Problemen zu erzählen. (his)
Wenn ________ Taschenrechner ________ Geschichte hätte, wäre es peinlicher als ________ Browsergeschichte. (my) (a) (my)
Ich habe ________ Socken gegessen, weil die Leute im ________ Internet es mir gesagt haben. (a) (the)
Schließlich ist es noch ________ Wahl. (a)
Was ist auf ________ Skala von eins bis zehn ________ Lieblingsgeschmack von zufälliger Grammatik? (a) (your)
Er ist in ________ Boy Band ________ ist für ________ Snake nicht viel Sinn. (a) (which) (a)
Er wartete darauf, dass ________ Stoppschild zu ________ GO -Schild sich wandte. (the) (a)
________ ist viel schwieriger, Tennis mit ________ Bowling Ball zu spielen, als mit ________ Tennisball zu blockieren. (It's) (a) (a)
________ Green Tea und Avocado Smoothie waren genau wie zu erwarten. (The)
Wenn niemand in der Nähe ist, klatschen ________ Bäume über ________ Menschen, die darunter gegangen sind. (the) (the)
Sie wollte ________ Pet Platypus, bekam aber stattdessen ________ Ente und ________ Frettchen. (a) (a) (a)
In diesem Moment erfuhr er, dass es bestimmte Teile des ________ Körpers gibt, den Sie niemals nair sollten. (the)
Er erkannte, dass es mehrere Todesfälle auf dieser Straße gegeben hatte, aber ________ besorgte sich, als er ________ genaue Anzahl sah. (his) (the)
________ donnerndes Brüllen von ________ Jet Overhead bestätigte ________ schlimmste Ängste. (The) (the) (her)
________ Bester Schlüsselkuchen ist immer noch zur Debatte. (The)
Verschiedene Meeresvögel sind elegant, aber nichts ist so elegant wie ________ Gleitpelikan. (a)
Erdnussbutter und Gelee ließen ________ ältere Dame über ________ Vergangenheit nachdenken. (the) (her)
Er machte sich auf den Weg zum kurzen Spaziergang, aber jetzt konnte er nur Mangroven und Wasser kilometerweit sehen. (a)
Alle waren neugierig auf ________ Large White Blimp, das über Nacht erschien. (the)
________ Tsunami Wave stürzte gegen ________ erhöhte Häuser und brach ________ Stapel, als wären sie Zahnstocher. (The) (the) (the)
Sie gingen in die ________ Strange Tiki Bar am ________ Rand der kleinen Strandstadt. (a) (the) (the)
________ Tourbus war voller Mädchen im Teenageralter, die auf ________ Nächstes Abenteuer zusteuerten. (The) (their)
________ Haar wurde windgepeitscht, als sie in ________ Schwarzes Cabrio ritt. (Her) (the)
Das Lightning Paradise war ________ lokaler Hangout -Gelenk, in dem die ________ Gruppe normalerweise ________ Nacht verbrachte. (the) (the) (the)
________ dickes Laub und miteinander verflochtene Reben ________ Wanderung fast unmöglich. (The) (the)
Als ________ Mietwagen zu ________ Halt auf der ________ Dunklen Straße rollte, nahm die Angst ________ Angst im Moment zu. (the) (a) (the) (her) (the)
________ neu gepflanzte Bäume wurden von Holzrahmen aufgehalten, in der Hoffnung, dass sie ________ im nächsten Sturm überleben konnten. (The) (the)
________ schroffer alter Mann saß in ________ zurück im ________ Ködergeschäft, der vor sich hin murrte, als er ________ Handvoll Würmer herausholte. (The) (the) (the) (a)
Alles, was sie sehen konnten, war ________ blaues Wasser, das ________ Segelboot umgab. (the) (their)
________ Das Dringing Care Center wurde mit Patienten überflutet, nachdem ________ Nachrichten über ________ New Deadly Virus veröffentlicht worden waren. (The) (the) (a)
________ Schild sagte, es sei eine Straßenarbeit vor sich, also beschloss er, sich zu beschleunigen. (The)
________ Haifisch infiziertes South Pine Channel war ________ nur ein oder out. (The) (the)
Er entschied, dass der Wasserkreiser auf dem ________ Frozen Lake keine gute Idee war. (a) (a)
Es war immer gefährlich, mit ihm zu fahren, da er darauf bestand, dass ________ Sicherheitszapfen ________ Slalom -Verlauf waren. (the) (a)
Sie war ________ Mädchen, das in ________ Pink House leben wollte. (the) (a)
________ Leben in ________ Grenzen von ________ House wurde ________ NEU NOW NORMAL. (Her) (the) (the) (her)
________ Near-Tod-Erfahrung brachte neue Ideen ans Licht. (The)
Sie waren aufgeregt, ________ First Faultier zu sehen. (their)
________ wach hinter ________ Boot von ________ Vergangenheit erzählt, während ________ Open Sea für das Leben in ________ Unbekannter Zukunft geöffnet wurde. (The) (the) (the) (the) (the)
Obwohl er glaubte, dass ________ Welt flach war, sah er nicht, wie er ________ Ironie hatte, um ________ Welt zu reisen. (the) (the) (the)
Er fragte sich, ob es ________ Beach genannt werden könnte, wenn es keinen Sand gab. (a)
Der Oberschenkel in ________ Wasser, ________ Fischer Hoffnung auf das Abendessen wurde bald in Verzweiflung. (the) (the)
________ kleine weiße Bojen markiert ________ Ort von Hunderten von Krabbentöpfen. (The) (the)
________ schneebedeckter Weg war keine Hilfe, um ________ aus dem Hinterland herauszufinden. (The) (his) (the)
________ Kellnerin war nicht amüsiert, als er grüne Eier und Schinken bestellte. (The)
Er hoffte, dass ________ Batterien tief in ________ Schnee in ________ Avalanche Beacon waren. (the) (his) (his)
Ich respektiere niemanden, der ________ Unterschied zwischen Pepsi und Cola nicht erzählen kann. (the)
Wenn ________ Jahre vergangen sind, wissen wir alle, wie die Besitzer ________ Hunde immer mehr aussehen. (the) (their)
In der Hoffnung, ________ Wahrheit herauszufinden, trat er in die Bibliothek in der ________ Ein-Zimmer-Bibliothek ein. (the) (the)
Als er ________ Kirche betrat, konnte er ________ weiche Stimme von jemandem hören, der in das Handy ________ flüsterte. (the) (the) (a)
Er betrat das ________ Museum leise, als ________ Super Bowl begann. (the) (the)
________regen ________ Windschutzscheibe als ________ Dunkelheit verschlang uns. (The) (the) (the)
Strandkämpfer ersetzte die Weinprobe als ________ neue Besessenheit. (his)
________ blinkende Lichter des ________ Antennen -Turms kamen in den Fokus, als ich ________ lautes Schnappschuss hörte. (The) (the) (a)
Autosicherheitssysteme sind ________ langweit gekommen, aber er wollte beweisen, dass sie überlistet. (a)
Sie sahen zu ________ Himmel auf und sahen ________ Millionen Sterne. (the) (a)
Sie öffnete ________ dritte Flasche Wein der ________ Nacht. (her) (the)
Mit ________ Single Flip of ________ Münze änderte sich das Leben für immer für immer. (a) (the) (his)
________ Tart Limonade löscht ________ Durst, aber nicht ________ Sehnsucht. (The) (her) (her)
Er war ________ Typ, der in ________ Mitte Juli Weihnachtslichter im ________ Haus mochte. (the) (his) (the)
Kleinkinder, die Waschbären füttern, überraschte sogar ________ erfahrene Park Ranger. (the)
Sie war angewidert, dass er ________ Unterschied zwischen Limonade und Limeade nicht sagen konnte. (the)
Immer wenn er ________ rote Fahnenwarnung am ________ Beach sah, griff er ________ Surfbrett. (a) (the) (his)
Zwilling 4 Monate alte, schlief im ________ Schatten der ________ Palme, während ________ Mutter in ________ Sonne gebräunt war. (the) (the) (the) (the)
Er trug nachts immer ________ Sonnenbrille. (his)
________ Dreijähriges Mädchen rannte ________ Beach runter, als ________ Kite hinter ihr flog. (The) (the) (the)
Während er am ersten Date ________ er hat versehentlich ________ Kopf auf ________ Strahl getroffen. (the) (his) (the)
________ Scream zum Schweigen gebracht ________ Rowdy -Teenager. (Her) (the)
Nachdem er ________ verlassenes Gebäude erkundet hatte, begann er an Geister zu glauben. (the)
________ Ansicht vom ________ Lighthouse begeistert sogar ________ am erfahrensten Reisenden. (The) (the) (the)
Er fragte sich, ob sie sich ________ Zehennagelsammlung schätzen würde. (his)
________ Sohn witzelte, dass Power Bars nichts anderes als Bonbonbars für Erwachsene waren. (His)
Strumpfhosen und Absätze sind eine interessante Wahl der Kleidung für ________ Beach. (the)
Sie tanzte ________ Happy Dance, weil alle ________ Socken von ________ Trockner übereinstimmten. (a) (the) (the)
Als sie ________ Guy, der versuchte, ________ abzuholen, nicht mochte, begann sie, Gebärdensprache zu verwenden. (a) (her)
________ leckeres Aroma aus ________ Küche wurde durch Zigarettenrauch ruiniert. (The) (the)
Schwimmen bei ________ eigenem Risiko wurde als ________ Herausforderung für die ________ Gruppe der Studenten der Kansas City College angesehen. (your) (a) (the)
Sie fragte sich, was ________ Augen unter ________ gespiegelten Sonnenbrille sagten. (his) (his)
________ Ameisen genossen ________ grillen mehr als ________ Familie. (The) (the) (the)
Sie taten nichts, da ________ Waschbär ________ Lady's Tasche mit Essen angegriffen hat. (the) (the)
Als er am ________ Beach picken musste, legte er absichtlich Sand in das Essen anderer Menschen. (the)
________ Trick, um Kinder dazu zu bringen, etwas zu essen, ist, um es zu sammeln. (The)
________ Schönheit des ________ Sonnenuntergangs wurde durch ________ Industriekrane verdeckt. (The) (the) (the)
Er stampfte auf ________ Fruchtschleifen und wurde somit zu ________ Müslischkiller. (his) (a)
Er betrat ________ Keller mit ________ Horrorfilm von ________ Nacht, bevor er in ________ Kopf spielte. (the) (the) (the) (his)
Sie sah ________ Bremslichter, aber nicht rechtzeitig. (the)
Egal wie schön ________ Sonnenuntergang ist, es war traurig, dass sie weiß, dass sie eines Tages älter war. (the) (her)
Sie lebte in der Affen -Dschungelstraße und das schien die ganze Fremdheit ________ zu erklären. (her)
Wenn Autofahrer in den Verkehr und aus dem Verkehr rasten, konnte sie nur diejenigen vorstellen, die ________ Transplantation benötigen. (a)
________ Tortoise sprang in den ________ See und träumte davon, ________ Meeresschildkröte zu werden. (The) (the) (a)
Für ________ 216. Mal sagte er, er würde nach dieser letzten Cola aufhören, Soda zu trinken. (the)
Luzifer war überrascht über ________ Leben im Death Valley. (the)
Es waren sechzehn Tage her, seit ________ Zombies zum ersten Mal angegriffen wurde. (the)
Charles aß ________ Pommes Frites und wusste, dass sie ________ letzte Mahlzeit sein würden. (the) (his)
Sie hatte ________ Geschenk, Lieder zu malen. (the)
Carol trank ________ Blut, als wäre sie ________ Vampir. (the) (a)
Dolores hätte nicht ________ Mahlzeit gegessen, wenn sie gewusst hätte, was es tatsächlich war. (the)
Grüße aus ________ echtem Universum. (the)
Es gibt ________ Nachricht für Sie, wenn Sie nachschlagen. (a)
Er fand ________ Schokoladenbedeckte Kakerlaken ziemlich lecker. (the)
Es wurde ________ klar, dass andere ________ glücklicher machen konnten, aber nur sie konnte sich glücklich machen. (her) (her)
Sie kippte ________ zurück und ließ die Peitsche Creme in den Mund in den Mund streamen, während sie ________ Bad nahm. (her) (her) (a)
Jeanne wünschte, sie hätte ________ Red Button gewählt. (the)
Es war ________ Erste Erfahrung beim Training ________ Rainbow Einhorn. (her) (a)
Er benutzt Onomatopoeia als ________ Waffe der geistigen Zerstörung. (a)
Das Wetter ist nicht trivial - ________ besonders wichtig, wenn Sie darin stehen. (it's)
________ ________ Skateboard -Pinguin mit ________ Sunhat! (It's) (a) (a)
Wenn Sie Zehennägel nicht mögen, sollten Sie sich wahrscheinlich nicht ________ Fuß ansehen. (your)
Wir werden Ihnen nicht erlauben, ________ Pet Armadillo mitzubringen. (your)
Als er zum ersten Mal ________ auf Mais stieß, fand er es unglaublich kitschig. (the)
Er war immer verwirrt zwischen Soldaten und Schultern, aber als ________ Militärmann verantwortlich. (a)
Von Kindern zu kindisch zu kindlich zu gehen ist nur ________ Zeit. (a)
________ Zahnarzt sagt mir, dass Kauen von Ziegeln für ________ Zähne sehr schlecht ist. (My) (your)
Er war enttäuscht, als er ________ Beach so sandig und ________ Sonne so sonnig fand. (the) (the)
Ich würde mich freuen, wenn ________ Meer voller Gurkensaft wäre. (the)
________ Busker hoffte, dass ________ Menschen, die an vorbeikamen, Geld werfen würden, aber sie warfen stattdessen Tomaten, so dass er ________ Hut gegen ________ Juicer tauschte. (The) (the) (his) (a)
Ich komme vom ________ Stamm der Headjäger, also werde ich niemals ________ Schrumpf brauchen. (a) (a)
Sie sind gut in Englisch, wenn Sie ________ Unterschied zwischen ________ Mann essen, das Hühnchen isst und ________ Mannfressendes Hühnchen. (the) (a) (a)
________ Pet Shop bietet alles, was Sie brauchen, um ________ Anaconda glücklich zu machen. (The) (your)
Dieses Buch verweigert sich sicher ________ Gehirn. (your)
Menschen, die darauf bestehen, ________ Zähne mit ________ Ellbogen zu wählen, sind so nervig! (their) (their)
Er praktiziert gerne ________ Ballett im ________ Badezimmer. (his) (the)
Trennungsangst ist das, was passiert, wenn Sie ________ Telefon nicht finden können. (your)
Verbessern Sie die körperliche Fitness von ________ Goldfisch, indem Sie ihn ________ Fahrrad bekommen. (your) (a)
________ Känguru ist wirklich nur ________ Kaninchen auf Steroiden. (A) (a)
Bei der Transplantation von Sämlingen erleichtern kandierte Teekannen. (the)
Bevor er nach ________ Innenstadt zog, hatte er immer geglaubt, dass Sicherheitskomplexe psychologisch waren. (the)
Paar ________ Designer Cowboyhut mit Tauchausrüstung für ________ unvergessliche Anlässe. (your) (a)
Für Ölflecken auf dem Boden ________ ist nichts über das Parken von ________ Motorrad in der ________ Lounge. (the) (a) (the)
Auf den Vorstellungsgesprächen auf dem Kopf stehen ________ ________ dauerhaften Eindruck. (a)
Nichts ist so vorsichtig kuschelig wie ________ Pet Porcupine. (a)
Niemand hat auf einen explosiven Gänseblümchen gestoßen und hat gelebt, ________ Geschichte zu erzählen. (the)
Eisenpyrit ist ________ für alle Mineralien. (the)
________ Anzug der Rüstung bietet an heißen Tagen einen hervorragenden Sonnenschutz. (A)
Ich bin ________ Tante der Schwester der Schwester. (my)
Die Weisheit kann leicht erworben werden, wenn Sie sich unter ________ Bett mit ________ Topf auf ________ Kopf verstecken. (the) (a) (your)
Jeder sollte Chaucer lesen, um ________ alltägliches Wortschatz zu verbessern. (their)
Er ist kein James Bond;________ Name ist Roger Moore. (his)
Ich mag es, die Arbeit nach ________ achtstündiger Tee-Break zu verlassen. (my)
Das Aufstehen im Morgengrauen ist für ________ Vögel. (the)
Wenn das Essen von Drei-Ei-Omeletts Gewichtszunahme verursacht, sind Blockgieeier ________ ein guter Ersatz. (a)
Shakespeare war ________ berühmter Dieselmechaniker aus dem 17. Jahrhundert. (a)
Schlagen Sie mich mit ________ Haustierhai! (your)
________ Japaner Yen für den Handel ist noch bekannt. (The)
________ Guinea Geflügel fliegt durch ________ Luft mit allen ________ Gnade von ________ Turtle. (The) (the) (the) (a)
Flauschige rosa Einhörner sind ________ populäres Statussymbol unter Macho -Männern. (a)
Dan nahm ________ Tauchgang ________ Kaninchenloch. (the) (the)
Erin schuf versehentlich ________ neues Universum. (a)
________ Tür auf ________ Wassermelone zugeschlagen. (The) (the)
Rosa Pferde galoppierten über ________ Meer. (the)
Fliege Fisch flog an der ________ Raumstation. (the)
Er färbte den Deep Space ________ weiches Gelb. (a)
Dan aß ________ Wolken wie Baumwoll -Süßigkeiten. (the)
Er fand ________ Kobold in ________ Walnussschale. (a) (his)
Bill rannte von ________ Giraffe in Richtung ________ Delphin. (the) (the)
Es machte keinen Sinn, es sei denn, Sie hatten ________ Kraft, Farben zu essen. (the)
Patricia liebt ________ Klang von Nägeln, die stark gegen ________ Tafel gepresst werden. (the) (the)
Er verstand nicht, warum ________ Bird ________ Fahrrad fahren wollte. (the) (the)
Knoblaucheis war ________ Favorit. (her)
Smoky ________ Bär begann heimlich mit ________ Feuer. (the) (the)
Pat bestellte ________ Ghost Pepper Pie. (a)
Sie haben das Recht, wütend zu sein, aber das gibt Ihnen nicht das Recht, gemein zu sein. (the)
Andy liebte es, auf dem ________ Nagelbett zu schlafen. (a)
________ tägliches Ziel war es, sich gestern zu verbessern. (Her)
Sie hatte ________ Angewohnheit, Schauer in Limonade zu nehmen. (a)
________ Elefant wollte nicht über ________ Person in ________ Zimmer sprechen. (The) (the) (the)
________ Skelett hatte Skelette von ________ in ________ Closet. (The) (his) (the)
Selbst wenn ________ Schnee draußen fiel, fühlte sie es angemessen, ________ Bikini zu tragen. (the) (her)
Er war sich sicher, dass ________ Teufel Red Farkly Glitter geschaffen hat. (the)
Er trug die ________ chirurgische Maske in der Öffentlichkeit, um nicht das ________ Virus zu fangen, sondern um die Menschen von ihm fernzuhalten. (the) (a)
Doris genoss es, ________ Nägel auf ________ Tisch zu tippen, um alle zu ärgern. (her) (the)
Niemand stellt in Mexiko ________ Pyramiden in Frage. (the)
Er dachte, ________ waren nur wenige Sticks Dynamit leichter als ________ Fischereistange, um Fische zu fangen. (a) (a)
Wenn das Geld knapp war, würde er ________ Mittagessen von ________ lokaler Wünsche bekommen. (his) (the)
________ Vater starb während der Geburt. (The)
Leguane fielen aus ________ Bäumen. (the)
Ich habe ________ Freund in Babyöl bedeckt. (my)
Jetzt muss ich über ________ Existenz nachdenken und mich fragen, ob ich wirklich real bin (my)
Ich habe lebende Ofen. (a)
Bitte sagen Sie mir, dass Sie nicht in ________ Leichenhalle arbeiten. (a)
Wir haben junge Kinder, die aus verschiedenen Gründen, einschließlich Clowns in ________ Closet, oft in ________ Zimmer gehen. (our) (the)
8% von 25 sind ________ wie 25% von 8 und einer von ihnen ist in ________ Kopf viel einfacher zu tun. (the) (your)
Sie beißen wegen ________ Unterkiefers. (your)
Die meisten Haiangriffe treten etwa 10 Fuß vom ________ Strand entfernt auf, da dort ________ Menschen sind. (the) (the)
Ich arbeite auf ________ Süßkartoffelfarm. (a)
David zeichnet ________ "Zelt ________ Zelt in ________ Bag" Strategie über das Schöne zusammen, um sie zu falten. (the) (your) (the)
Ich bin ________ großer Zuhörer, wirklich gut mit Empathie gegen Sympathie und all dem, aber ich hasse Menschen. (a)
Wenn ich Spaghetti koche, koche ich es gerne ________ ein paar Minuten nach Al -Dente, damit ________ Nudeln super rutschig sind. (a) (the)
Er entschied, dass ________ Zeit stärker war als alle ________ Ausreden, die er bis dahin benutzt hatte. (the) (the)
________ Tür schwang sich auf, um rosa Giraffen und rote Elefanten zu enthüllen. (The)
Sie reiste, weil es ________ wie die Therapie kostete und ________ viel angenehmer war. (the) (a)
________ Pinbrush war wütend auf ________ Farbe ________ Künstler entschied sich für die Verwendung. (The) (the) (the)
________ Bienen beschlossen, ________ Meuterei gegen ________ Königin zu haben. (The) (a) (their)
________ Ultimate Dream Fantasy bestand darin, zufrieden zu sein und acht Stunden in ________ Reihe zu schlafen. (His) (a)
Sie schaute in ________ Spiegel und sah eine andere Person. (the)
In ________ Welt sind nicht genug Handtücher, um das Abwasser aus dem Mund zu stoppen. (the) (the) (his)
Er hatte ________ vage Gefühl, dass Bäume Dinosaurier geboren haben. (a)
________ Puppe drehte sich in Kreisen um, in der Hoffnung, lebendig zu werden. (The)
Traubengelee löste ________ Loch in ________ Dach aus. (the) (the)
Schokoladenbedeckte Grillen waren ________ Lieblingssnack. (his)
________ Secret Code, den sie erstellt haben, machte für sie keinen Sinn. (The)
Drei Jahre später war ________ Sarg immer noch voller Jello. (the)
________ Verstand wurde geblasen, dass es nichts im Raum außer dem Raum selbst gab. (His)
Sie spielen ________ Klavier, während sie im ________ Flugzeug fliegen. (the) (the)
________ Händedesinfektionsmittel war tatsächlich ein klarer Kleber. (The)
________ Texte des ________ Songs klangen wie Fingernägel auf ________ Chalkboard. (The) (the) (a)
Es dauerte ________ Monat, um das ________ Mahlzeit zu beenden. (a) (the)
Er goss Felsen in ________ Dungeon von ________ Verstand ein. (the) (his)
________ Blue Papagei fuhr mit ________ Hitchhiking -Mongoose. (The) (the)
Glück kann in ________ Tiefen des Schokoladenpudding gefunden werden. (the)
Es gibt keine Helden in der ________ Punkrockband. (a)
Er rasierte ________ Pfirsich, um ________ Punkt zu beweisen. (the) (a)
________ schwer zu verstehen ________ Längen, er würde kurz bleiben. (It's) (the)
Er schuf ________ Pig Burger aus Rindfleisch. (a)
________ Denkprozess war auf so vielen Ebenen, dass er sich ________ Phobie der Höhen gab. (His) (a)
Er spielte gern mit Worten in ________ Badewanne. (the)
Es gab drei Kugelfelsen, die sich im ________ gewechsten Raum versammelten. (a)
Es war nicht abzusehen, welche Gedanken von ________ Machine kommen würden. (the)
Er legte ________ Wunde Hitze, um zu sehen, was wachsen würde. (the)
Sie benutzte ________ eigene Haare in ________ Suppe, um ihm mehr Geschmack zu verleihen. (her) (the)
________ Spielzeug brachte gute Erinnerungen daran zurück, in ________ Regenwald verloren zu gehen. (The) (the)
Sie konnte sich nicht entscheiden, dass ________ Glas halb leer oder halb voll war, also trank sie es. (the)
Er war nicht bitter, dass sie weitergezogen war, aber von ________ Rettich. (the)
Er hatte beschlossen, das Schicksal des Schicksals zu akzeptieren. (his) (his)
________ Wolken bildeten schöne Tiere im ________ Himmel, die schließlich ________ Tornado zum Chaos anrichten. (The) (the) (a)
________ wirbte Lollipop mit ________ Pop -Rock -Süßigkeiten. (The) (the)
Er nahm Müll in ________ Freizeit auf, um in den Hof des Nachbarn zu werfen. (his) (his)
________ Fisch träumte davon, ________ Fishbowl in die ________ Toilette zu entkommen, wo er ________ Freund gehen sah. (The) (the) (the) (his)
Es war ________ wirklich guter Montag, dass er ________ Samstag war. (a) (a)
Grüße von ________ Galaxy MACS0647-JD oder was wir zu Hause nennen. (the)
Er war überrascht, dass ________ immense Faulheit für andere inspirierend war. (his)
Er hatte den Schlafwandeln unwissentlich als ________ Nachthobby aufgenommen. (a)
Er stieß ________ Haargrün, um ________ Iguana zu unterstützen. (his) (his)
________ Fünfzig Mannequin -Köpfe, die in ________ Pool schweben, haben sie irgendwie ausgeflippt. (The) (the)
Obwohl es nicht ________ Pot Gold war, war Nancy immer noch begeistert von dem, was sie am ________ Ende von ________ Rainbow fand. (a) (the) (the)
Nachdem Brian gegen ________ Alligator gekämpft hatte, musste er sich immer noch mit ________ Anaconda stellen. (the) (the)
Es dauerte nicht lange, bis Gary festgestellt hat, dass ________ Räuber Amateure waren. (the)
Er umarmte ________ neues Leben als Aubergine. (his)
Karen erkannte, dass ________ nur so wie sie in den Himmel kam, zu betrügen. (the)
Er liebte es, ________ Bananen in Hot -Dog -Brötchen zu essen. (his)
Dreißig Jahre später fand sie immer noch, dass es in Ordnung war, ________ Toilettenpapierrolle unter als vorbei zu setzen. (the)
Er sah sich ________ größte Angst vor und aß ________ First Marshmallow. (his) (his)
Er fand, dass ________ Kunst nie fortgeschritten war, als er ________ Schweiß und Tränen buchstäblich benutzte. (his) (his)
Nancy war stolz darauf, dass sie ________ eng mit dem Schiffswrack lief. (a)
Es brauchte ________, bis er erkannte, dass alles, was er sich nicht veränderte, tatsächlich entschied. (a)
Es war schwierig für Mary zuzugeben, dass das meiste ________ Training aus einem schlechten Urteilsvermögen bestand. (her)
Jason lebte ________ Leben nach ________ Motto: "Alles, was es wert ist, es zu tun, lohnt sich schlecht. (his) (the)
David absolvierte stolz die High School Top in der ________ Klasse im Alter von 97 Jahren. (his)
________ Mord Hornet war enttäuscht von ________ vorgefassten Ideen, die Menschen von ihm hatten. (The) (the)
________ Zwei gingen entlang ________ Slot Canyon, der in ________ Distanz ________ Donnern ________. (The) (the) (the) (the)
Sie war erstaunt über ________ große Eisbrocken am ________ Beach. (the) (the)
________ Beach war voller Schneeleoparden. (The)
Als ________ Asteroid zur Erde rast, war Becky verärgert ________ Zahnarzttermin wurde abgesagt. (the) (her)
Sie sah sich ________ Meisterwerk an, das im ________ Museum hing, aber sie konnte nur denken, dass ________ Fünfjährige es besser machen konnte. (the) (the) (her)
________ White Water Rafting Trip wurde plötzlich durch ________ unerwartete Mauer angehalten. (The) (the)
Sie hatte immer eine interessante Perspektive, warum ________ Welt flach sein muss. (the)
________ plötzlicher Regensturm wusch Krokodile in ________ Ozean. (The) (the)
Harrold war zuversichtlich, dass niemand jemals ________ Spionagepigeon vermuten würde. (his)
Er wusste, dass es ________ Bad Day sein würde, als er sahen, wie Berglöwen ________ Straßen streifen. (a) (the)
Er beschloss, ________ Verschwinden zu fälschen, um ein Gefängnis zu vermeiden. (his)
Am Ende brannte er ________ Finger, die das Feuer eines anderen stupsen. (his)
Sie hatte ________ schwierige Zeit, sich auf ________ eigenes verrücktes Selbst zu besitzen. (a) (her)
Sie hatte diese Tönung der Verrücktheit in der ________ Seele, die ________ glaubte, sie könnte ________ Unterschied machen. (her) (her) (a)
Sie machte sich nur vorwärts, weil sie vertraute, dass ________ Ende sie jetzt durchging. (the) (a)
Während alle ________ Freunde sicher waren, dass Mary ________ Sechster Sinn hatte, wusste sie, dass sie tatsächlich ________ siebten Sinn hatte. (her) (a) (a)
Er hatte ________ Wand voller Masken, damit sie jeden Tag ________ ein anderes Gesicht tragen konnte. (a) (a)
________ Gruppe verstand schnell, dass giftiger Abfall ________ am wirksamsten gegen ________ Zombies war. (The) (the) (the)
Es gab Tage, an denen ich von ________ Körper getrennt werden wollte, aber heute war heute keines dieser Tage. (my)
Zu ________ Überraschung aller, ________ Entrückung ist gestern passiert, aber es verlief nicht ganz wie erwartet. (the) (the)
________ Bullet durchbohrte ________ Fenster, das es zerschmetterte, bevor Dannys Kopf durch bloße Millimeter vermisst wurde. (The) (the)
________ komplizierte Schulhausaufgaben ließen ________ Eltern versuchen, ________ Kinder ziemlich verwirrt zu helfen. (The) (the) (their)
________ externe Narben erzählen nur einen Teil der ________ Geschichte. (The) (the)
Die Aufregung ersetzte die Angst bis zum letzten Moment ________. (the)
________ zerfetzte Arbeitschuhe sprechen von ________ viele Stunden harter Arbeit, die er während des gesamten Lebens ertrug. (The) (the) (his)
________ Hummingbirds Flügel verschwommen, während es eifrig ________ Zuckerwasser von ________ Feeder nippte. (The) (the) (the)
Poison Ivy wuchs durch ________ Zaun, von denen sie sagten, dass sie undurchdringlich waren. (the)
Das Anschauen von ________ Geriatrischen Männerns Softball-Team brachte Erinnerungen an 3 Jahre alte, die T-Ball spielten. (the)
________ Teenager fragten sich, was in ________ Red Shed auf ________ weit des ________ Schulgeländes aufbewahrt wurde. (The) (the) (the) (the)
Er bemüht sich, ________ bester Rasen in der Nachbarschaft in ________ zu halten. (the) (the)
________ Spa -Begleiter ________ Tiefe Reinigungsmaske auf ________ Gentleman's Rücken. (The) (the) (the)
Die Farbe der Schindel war nicht etwas, worüber ________ Ehepaar jemals gesprochen hatte. (the)
________ Sunblock wurde vor dem Training an ________ Mädchen übergeben, aber ________ verbrannte Haut war ein Beweis dafür, dass sie sie nicht aufgetragen hat. (The) (the) (the)
________ Virus hatte Befugnisse, die keiner von uns wusste. (The)
________ Quiet House ist schön, bis Sie befohlen werden, monatelang darin zu bleiben. (A)
Im Laufe der Zeit verwandelten sich einfache Hundebefehle in vollständige Absätze, in denen erklärt wurde, warum ________ Dog nichts nicht tun konnte. (the)
Mütter verbringen monatelanges Leben ________ Leben auf ________ Kinder. (their) (their)
________ Teammitglieder waren schwer zu unterscheiden, da sie alle ________ Haare in ________ Pferdeschwanz trugen. (The) (their) (a)
________ Argument war auf dem ________ Parkplatz zu hören. (Their) (the)
Anweisungen, dass ________ Berge ________ Westen sind, funktioniert nur, wenn Sie sie sehen können. (the) (the)
Das Reisen wurde während der ________ Pandemie fast ausgestorben. (the)
________ Great Dane sah eher nach ________ Pferd als ________ Hund aus. (The) (a) (a)
Er spielte ________ Spiel, als ob ________ Leben davon abhing und ________ Wahrheit war, dass es das tat. (the) (his) (the)
________ nicht möglich, ________ Affen zu überzeugen, Ihnen ________ Banane zu geben, indem Sie es unendlich Bananen versprechen, wenn sie sterben. (It's) (a) (a)
Er ging auf ________ Whisky -Diät und verlor sofort drei Tage. (a)
Er sah zu, wie ________ Ferkel mit Panda Bear -Bäuchen im ________ Schwimmbad tanzte. (the) (the)
Martha kam zu ________ Schlussfolgerung, dass Shake -Gewichte ________ tolles Geschenk für jeden Anlass sind. (the) (a)
Sie hatte ________ Kinder davon überzeugt, dass jeder auf ________ Boden gefundene Pilze sie töten würde, wenn sie ihn berühren würden. (her) (the)
Als sie ________ Street entlang ging und in ________ Gosse schaute, stellte sie fest, dass Gesichtsmasken zu ________ neuen Zigarettenstolben geworden waren. (the) (the) (the)
Mary erkannte, wenn ________ Taschenrechner ________ Geschichte hätte, wäre es peinlicher als ________ Computerbrowser -Geschichte. (her) (a) (her)
________ Baum fiel unerwartet kurz. (The)
Morgen wird etwas Neues bringen, also gehen Sie heute als ________ Gedächtnis. (a)
Heute habe ich ________ Einhorn in Vorbereitung auf ________ Rasse gekleidet. (my) (the)
Heute ist ich ________ Tag, den ich endlich wissen werde, wie Ziegel schmeckt. (the)
Heute haben wir Moss für ________ Onkels Hochzeit versammelt. (my)
Heute kam mit ________ Crash von ________ Auto durch ________ Garagentor. (a) (my) (the)
Sie dachte, es würde genügend Zeit geben, wenn sie ________ beobachten würde. (her)
Sie werden ________ Rainbow Bridge sehen, nachdem sie Katzen und Hunde regnet. (the)
________ Dead Ente fliegt nicht rückwärts. (A)
Ich dachte, Red hätte sich im Sommer wärmer gefühlt, aber ich dachte nicht an ________ Equator. (the)
Blau klang zu ________ Zeit zu kalt und dennoch schien es für Gin zu funktionieren. (the)
Warmes Bier am ________ Cold Day ist nicht ________ Idee des Spaßes. (a) (my)
Ehrlich gesagt hat es mir für ________ in der ersten Staffel egal, also habe ich mich nicht um ________ zweite gekümmert. (the) (the)
________ Licht, das doppelt so hell brennt, brennt halb so lang. (The)
Ich mochte ________ die ersten beiden Alben, änderte aber ________ nach diesem Wohltätigkeitsorganisation. (their) (my)
Sie verbesserten sich dramatisch, sobald ________ Sänger gegangen ist. (the)
Sie brauchten dringend einen anderen Schlagzeuger, da ________ Current nur wusste, wie man Bongos spielt. (the)
Halten Sie sich an, ________ Kätzchen kratzen an der Badewanne von ________ und sie werden durch ________ Mangel an Keksen verärgert. (my) (the) (the)
________ Tränen von ________ Clown machen ________ Lippenstift laufen, aber ________ Duschkappe ist immer noch intakt. (The) (a) (my) (my)
________ Handschuhe schützen ________ Fuß vor überschüssigen Arbeiten. (The) (my)
________ Nebel war so dicht, selbst ________ Laser entschied, dass es keine Anstrengung wert war. (The) (a) (the)
________ Golden Retriever liebte das ________ Feuerwerk jeden vierten Juli. (The) (the)
Ich möchte ________ Giraffe, aber ich bin ________ Turtle esse Waffeln. (a) (a)
Henry konnte sich nicht entscheiden, ob er ein Auto -Mechaniker oder ein ________ Priester war. (a)
100 Jahre alt ist ein so ________ junges Alter, wenn Sie ________ Bristlecone Pine sind. (a) (a)
Als er ________ Lieblingsnummer fragte, antwortete sie ohne zu zögern, dass es sich um Diamanten handelte. (her)
________ größte Freude ist es, Mandeln zu rösten und Beute zu verfolgen. (My)
Edith könnte entscheiden, ob sie ________ Zähne malen oder ________ Nägel putzen sollte. (her) (her)
Es war ________ zum ersten Mal, als er jemals jemanden auf einem Elefanten kochen sah. (the)
Lila ist ________ Beste Stadt im ________ Wald. (the) (the)
Es gibt kein besseres Gefühl, als mit geschlossenen Augen auf ________ Wand zu starren. (a)
Sie konnte nicht verstehen, warum niemand sehen konnte, dass ________ Himmel voller Baumwoll -Süßigkeiten ist. (the)
Er beschloss, alle ________ Sand am Strand ________ als ________ Hobby zu zählen. (the) (the) (a)
________ Onkels Lieblingsbeschäftigung war es, Autos aus Nudeln zu bauen. (My)
________ Der beste Teil der Ehe sind Tiercracker mit Erdnussbutter. (The)
Es gibt über 500 Seestern in ________ Badezimmerschublade. (the)
Sie bestand darauf, dass die Reinigung von ________ Closet ________ Schlüssel zum guten Fahren war. (your) (the)
Situps sind ________ schreckliche Art, ________ Tag zu enden. (a) (your)
Kursives Schreiben ist ________ am besten, um eine ________ Rennstrecke zu erstellen. (the) (a)
________ Bird hatte ________ Glaube, dass es wirklich ________ Groundhog war. (The) (a) (a)
Jenny machte ________ Ankündigung, dass ________ Baby ein Außerirdischer war. (the) (her)
Er hatte das Gefühl, dass das Essen auf der ________ Brücke Romantik in die ________ Beziehung zu ________ Katze brachte. (the) (his) (his)
Sie war ________ Mädchen, das immer Zucker verbrannte, um zu zeigen, dass sie sich kümmerte. (the)
Ich war beleidigt durch ________ Vorschlag, dass ________ kleiner Bruder ________ Juwelendieb war. (the) (my) (a)
Nur weil ________ Wasser rot ist, heißt das nicht, dass Sie es nicht trinken können. (the)
Heute habe ich ________ Regenmantel gekauft und ihn am ________ sonnigen Tag getragen. (a) (a)
Ich wollte schon immer nach Tadschikistan gehen, aber ________ Katze würde mich vermissen. (my)
Ich habe früher in dem Fischteich des Nachbarn gelebt, aber ________ Ästhetik war nicht zu ________ Geschmack. (my) (the) (my)
Stellen Sie sich ________ Überraschung vor, als er feststellte, dass ________ Safe voller Pudding war. (his) (the)
Ich genieße nur Schaufensterbühne, wenn ________ Fenster transparent sind. (the)
Er war ________ nur Mitglied des ________ Clubs, der Plum Pudding nicht mochte. (the) (the)
Ich habe nach Komplimenten gefischt und versehentlich ________ Forellen gefangen. (a)
Es ist nicht wahr, dass ________ Matratze aus Baumwoll -Süßigkeiten besteht. (my)
Ich erhielt ________ schwere Geldstrafe, aber es konnte ________ Geist nicht zerquetschen. (a) (my)
Herr Montoya kennt ________ Way to ________ Bäckerei, obwohl er nie dort war. (the) (the)
Es ist nicht schwierig, ________ Handstand zu tun, wenn Sie nur auf ________ Händen stehen. (a) (your)
Erdbeeren müssen ________ ein Essen sein, das zu dieser Farbe nicht gut passt. (the)
________ Das Schlimmste an der Spitze von ________ Karriereleiter ist, dass es ________ langen Weg zum Herbst gibt. (The) (the) (the) (a)
Bringen Sie immer Zimtbrötchen auf ________ Tiefsee-Tauch-Expedition mit. (a)
Es gibt keinen Grund, warum ________ Hula Hoop nicht auch ________ Zirkusring sein kann. (a) (a)
Ich brauchte zu lange, um zu erkennen, dass die ________ Decke nicht gemalt worden war, um wie ________ Himmel auszusehen. (the) (the)
Sarah lief vom ________ Serienmörder und hielt ________ Krug mit Milch. (the) (a)
Gwen hatte ________ Beste Schlaf überhaupt auf ________ neues Nagelbett. (her) (her)
Douglas dachte, es war ________ Bester Weg, um erfolgreich zu sein, war es, das Gegenteil von dem zu tun, was er alle ________ Leben getan hatte. (the) (the) (his)
Patricia fand ________ Sinn des Lebens in ________ Schüssel mit Cheerios. (the) (a)
Das muss ________ Zehntes Mal sein, als ich wegen Verkaufs von frittierten Zigarren verhaftet wurde. (the)
Mit ________ Chief Raccoon, die nicht vertraut sind, schadeten ________ Aussichten für die Beförderung. (the) (his)
________ Anblick von ________ Ziegenbart ließ mich unter ________ Schwägerin des Schwägers rennen und verstecken. (The) (his) (my)
________ Der aufregendste Eureka -Moment, den ich hatte, war, als mir klar wurde, dass ________ Anweisungen zu Lebensmittelpaketen nur Richtlinien waren. (The) (the)
Es muss einfach sein, Verbrechen als ________ Schlange zu begehen, da Sie sich keine Sorgen machen müssen, Fingerabdrücke zu verlassen. (a)
Ich bin rundum in Afrika gereist und habe ________ GNU immer noch nicht gefunden, der ________ Schal gestohlen hat. (the) (my)
In diesem Moment war ich ________ am furchterregendsten Weasel in ________ ganzem Sumpf. (the) (the)
________ Chic Gangster begann gern ________ Day mit ________ Pink Schal. (The) (the) (a)
Sie wurde nur zum Präsidenten der Gesellschaft ernannt, weil sie mit ________ Zehen pfeifen kann. (the) (her)
________ Wechsel von Down -Bettdecken zu Baumwollbettbresen bedeutete immer, dass ________ Eichhörnchen zurückgekehrt waren. (The) (the)
Bellende Hunde und schreiende Kleinkinder haben ________ einzigartige Fähigkeit, freundliche Nachbarn in launische Feinde zu verwandeln. (the)
________ Furnace Reparaturman gab angegeben ________ Heizsystem als Klimaanlage. (The) (the)
________ Wasser floss runter ________ Fluss sah nicht so mächtig aus ________ Auto aus (The) (the) (the)
________ Brotteig erinnerte ________ an den Bauch von Santa -Klausel. (The) (her)
________ Gestank von ________ Feedlot durchdrungen ________ Auto trotz ________ Klimaanlage auf recycelter Luft. (The) (the) (the) (the)
Nancy beschloss, ________ Porta-Potty ________ nach Hause zu bringen. (the) (her)
Hektar Mandelbäume gesäumt ________ Interstate Highway ________ ergänzt ________ verrückte Fahrmuttern. (the) (which) (the)
________ Tumbleweed weigerte sich zu stürzen, war aber mehr als bereit zu pranzen. (The)
Nancy dachte, ________ Die beste Möglichkeit, ________ Begrüßung nach Hause zu kreieren, bestand darin, es mit Stacheldraht auszulegen. (the) (a)
________ Underground Bunker war mit Pommes und Süßigkeiten gefüllt. (The)
________ tote Bäume warteten darauf, von ________ kleinsten Funken entzündet zu werden und suchte ________ Rache. (The) (the) (their)
________ Überführung fuhr unter ________ Autobahn in ________ Secret World. (The) (the) (a)
________ Erhalten Sie reichhaltiges schnelles Schema, ________ Cactus Farm zu wachsen. (His) (a)
Siri wurde verwirrt, als wir wiederverwendet wurden, um ________ Anweisungen zu folgen. (her)
Mit ________ starker Windwarnung (the)
Sie fand es seltsam, dass die Leute ________ Handys verwenden, um tatsächlich miteinander zu sprechen. (their)
________ Der Wasserstand des Reservoirs setzte sich weiter, während wir ________ lange Dusche genossen. (The) (our)
Müll bedeckt ________ Landschaft wie Streusel tun ________ Geburtstagstorte. (the) (a)
________ Eiscreme-LKWs bringen schlechte Erinnerungen für uns alle zurück. (The)
Sie beendeten den Bau ________ Straße, von denen sie wussten, dass niemand jemals benutzen würde. (the)
Bei der Konfrontation mit dem ________ Rotary Dial -Telefon war ________ Teenager verwirrt. (a) (the)
________ Gletscher lebten lebendig, als ________ Kletterer näher wanderten. (The) (the)
Normale Aktivitäten dauerten außergewöhnliche Konzentrationsmengen in ________ großer Höhe. (the)
________ Hitze (The)
Felsbrocken ________ Seite von ________ Straße vorausgesagt, was als nächstes kommen könnte. (the) (the)
________ Zaun war verwirrt darüber, ob es die Dinge behalten oder die Dinge fernhalten sollte. (The)
Heimweh wurde in ________ junger Camper 'Hütte ansteckend. (the)
Der endlose Wutanfall des Kleinkindes verursachte ________ Ganzes Flugzeugangst. (The) (the)
________ Manager von ________ Obststand immer saß und verkaufte nur Gemüse. (The) (the)
________ Hawk verstand nicht, warum ________ Ground Eichhörnchen nicht ________ Freund sein wollte. (The) (the) (his)
Jim fuhr gern in der Stadt mit ________ Gefahrenleuchten. (his)
Mama hat nicht verstanden, warum niemand sonst ________ Whirlpool mit Jello wollte. (a)
Anstelle von ________ Junggesellenparty (a)
________ die Aufregung der Familie, nach Disneyland zu gehen, war verrückter als erwartet. (The)
________ alte verrostete landwirtschaftliche Ausrüstung ________ Haus, die seinen Tod voraussagen. (The) (the)
________ Duft der Wahl war frischer Knoblauch. (Her)
Jason verstand nicht, warum ________ Eltern ihn bei ________ Garagenverkauf ________ nicht verkaufen lassen würden. (his) (his) (the)
________ Vater reichte jedes Kind ________ Roadmap bei ________ Beginn des ________ 2-tägigen Roadtrips und erklärte, dass sie ________ nach Hause finden konnten. (The) (a) (the) (the) (their)
Im ________ Lagerhaus wurden mehr Wohnmobile als auf dem ________ Campground gesehen. (the) (the)
Als er an ________ Seil tief in der ________ Spalte baumelte (the) (the)
________ ältere Nachbarschaft wurde wütend über ________ Coyotes, die für das Verschwinden von ________ Pudel verantwortlich gemacht worden waren. (The) (the) (the)
________ Holzlöffel konnte nicht schneiden, sondern emotionale Narben hinterlassen. (The)
Kevin nahm ________ die Fähigkeit an, bei ________ falscher Zeit am falschen Ort zu sein. (his) (the) (the)
Sie entdeckte, dass das Leben von Van mit 2 Katzen und ________ Hund schwierig ist. (a)
Er träumte davon, ________ Anwaltskanzlei zu verlassen, um ________ tragbare Hundwäsche zu öffnen. (his) (a)
Trotz mehrerer Komplikationen und ________ Nahtoderfahrung (her)
________ Teenager wurde beschuldigt, ________ Arm gebrochen zu haben, einfach aus dem ________ Test herauszukommen. (The) (his) (the)
________ Bug hatte einen ausgezeichneten Tag, bis er ________ Windschutzscheibe traf. (The) (the)
Er war alle Geschäftstätigkeit, als er ________ Clown -Anzug trug. (his)
________ Miniatur -Haustier -Elefant wurde ________ Neid von ________ Viertel. (The) (the) (the)
________ Child's Lieblings -Weihnachtsgeschenk war ________ Large Box. (The) (the) (her)
________ Lama konnte nicht widerstehen, ________ Limonade zu versuchen. (The) (the)
Früher habe ich drei Stunden ________ Tag mit Spaghetti geübt, aber ich hörte auf, weil ich nicht alleine sterben wollte. (a)
Ich habe betrogen, als ich ________ Darts -Turnier spielte, indem ich ________ Longbow benutzte. (the) (a)
Ich hatte ________ Freund in der High School namens Rick Shaw, aber er war ziemlich nutzlos als Transportmittel. (a) (a)
________ Luftballons schwebten zusammen mit allen ________ Hoffnungen und Träumen. (The) (my)
Es gab ________ viele Gemälde von Affen, die Bambusstäbchen in der ________ Galerie schwenkten. (a) (the)
________ Anaconda war ________ größter krimineller Mastermind in diesem Teil der Nachbarschaft in ________. (The) (the) (the)
Sie sagen, die Menschen erinnern sich an wichtige Momente im ________ Leben gut, aber niemand erinnert sich an die eigene Geburt. (their) (their)
Ich begann mir Sorgen zu machen, dass ________ Pet Turtle erkennen konnte, was ich dachte. (my)
Ich habe immer davon geträumt, auf ________ Desert Island gestrandet zu werden, bis es tatsächlich geschah. (a)
________ wichtig, um sich zu erinnern, sich der tobenden Grizzlybären bewusst zu sein. (It's)
________ Immobilienmakler markierten schnell das ________ Territorium auf ________ Tanzfläche. (The) (his) (the)
Wenn Sie ________ Ohren wirklich belasten, können Sie nur ________ Klang von niemandem hören, der ________ verdammt gibt. (your) (the) (a)
Ich finde ________ ehrlich gesagt so einschüchternd wie ________ Korb von Kätzchen. (her) (a)
________ tröstet nie, dass ________ Schicksal von etwas abhängt, das so unvorhersehbar ist wie ________ Maisknall. (It's) (your) (the)
Trotz dessen, was ________ Lehrer Ihnen vielleicht gesagt hat, gibt es ________ falsch, ________ Lasso zu führen. (your) (a) (a)
Ich machte mich ________ Peanut Buttersandwich, da ich nicht von Gemüsecrackern leben wollte. (a)
________ Gutes Beispiel für ________ nützliches Gemüse ist medizinischer Rhabarber. (A) (a)
Ich wurde paranoid, dass die ________ School of Quallen auf mich ausspionierte. (the)
________ immer ________ Gute Idee, Schutz vor ________ Böser Blick der ________ Sonne zu suchen. (It's) (a) (the) (the)
Ich weiß, dass viele Kinder nach ________ Pony bitten, aber ich wollte ________ Fahrrad mit Raketen, die daran festgeschnallt sind. (a) (a)
Aus irgendeinem unergründlichen Grund betrachtete das ________ Response -Team ________ Mangel an Milch für ________ Müsli als ________ ordnungsgemäß. (the) (a) (my) (a)
Nachdem ich mich in Pflanzenöl beschichtet hatte, stellte ich fest, dass die Erfolgsrate von ________ in die Höhe geschossen wurde. (my)
________ Effizienz mit ________ er war sehr bewundernswert. (The) (which) (the) (the)
Ich bin kein ________ Partytier, aber ich mag Tierpartys. (a)
Ich habe noch nie ________ schöneres Brandyglas mit Wein gesehen. (a)
Alles lief so gut, bis ich von ________ Purple Giraffe angesprochen wurde. (a)
Es gibt ________ wachsende Trend bei Teenagern, Frisbees als Go-Cart-Räder einzusetzen. (a)
Sie haben kein Recht, sich kreativ zu nennen, bis Sie sich ________ Kelle ansehen und denken, dass es ________ großartiger Lockpick machen würde. (a) (a)
Ich kann nicht glauben, dass dies ________ Achtes Mal ist, dass ich am selben Tag auf ________ Piggy Bank zerschmettere! (the) (my) (the)
Es gibt wahrscheinlich genug Glas im ________ Schrank, um ein Unterwasseraquarium zu bauen. (my)
Ich mache mir Sorgen um die Tatsache, dass ________ Tochter ________ lokaler Teppichverkäufer als ________ Vorbild ansieht. (the) (my) (the) (a)
________ Sekretär ist ________ nur eine Person, die ________ Stempelkollektion wirklich versteht. (My) (the) (my)
________ war nie ________ Verantwortung, ________ Donuts zu glasieren. (It's) (my) (the)
`;
